name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_A800:
    uses: ./.github/workflows/huoshan-task-template.yml  # 模板文件路径
    with:
      task_config_template: .github/commons/template/huoshan-mltask-template.yaml
      task_cmd_file: .github/commons/scripts/huoshan_cmd.sh
      task_config_file: .github/commons/huoshan-mltask.yaml
      update_config_script: .github/commons/scripts/update_huoshan_config.py
      task_name: kairos-ci-${{ github.sha }}
      pendding_timeout: 1800
      taskid_file: huoshan_taskid.txt